import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Heading from "./components/Heading";
import Footer from "./components/footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <body
        className={`${inter.variable} antialiased bg-white font-sans`}
      >
        <Heading />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
